import 'package:flutter/material.dart';
import 'package:textendable/textendable.dart';

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Textendable(text: '''
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pretium cursus est, eu eleifend urna condimentum et. Aliquam eget ligula in diam laoreet placerat. Integer vitae tortor pharetra, tincidunt tortor in, aliquam lacus. Sed laoreet in nulla quis venenatis. Suspendisse euismod, sapien nec suscipit malesuada, enim arcu bibendum arcu, sed ullamcorper diam lorem nec massa. Duis eget commodo ante. In hac habitasse platea dictumst. Praesent rutrum dolor sed volutpat porttitor. Duis at odio sit amet risus porttitor maximus. Vestibulum ut turpis elit. Sed orci purus, malesuada a malesuada vitae, auctor sit amet erat. Nam dui turpis, lobortis ac enim sed, pulvinar commodo risus. Quisque posuere interdum dui, vitae facilisis ex congue vel. Etiam blandit a metus nec luctus. In vel metus tortor. Nulla eget faucibus quam.
         In fermentum justo quis enim facilisis lacinia. Integer vitae auctor turpis, et dapibus odio. Fusce ut convallis eros, at faucibus ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras vel nisi et leo aliquet lobortis. Suspendisse sodales fermentum odio faucibus ullamcorper. Suspendisse mi magna, tristique vel pretium sed, volutpat nec enim. Nunc ultrices ex nec arcu molestie molestie. In hac habitasse platea dictumst. Integer in maximus elit. Vivamus enim lacus, porta at cursus a, pharetra in nunc. Donec blandit mollis dui, id auctor diam tincidunt eu. Suspendisse vulputate id lacus lacinia suscipit. Donec rutrum felis et turpis faucibus lacinia.
         Integer consectetur dolor condimentum, molestie quam rutrum, congue purus. Pellentesque non enim consequat, faucibus lectus vel, faucibus risus. Phasellus finibus risus vel augue condimentum, rutrum tincidunt neque tincidunt. Donec justo magna, pulvinar ut consequat sed, pretium id lacus. Curabitur ut magna in libero interdum gravida. Aenean dolor risus, malesuada ut magna et, tempus gravida sapien. In hac habitasse platea dictumst. Donec id est gravida, eleifend nunc vel, placerat arcu. Nulla in rhoncus magna, eu consectetur justo. Cras rutrum posuere neque, non maximus sem maximus quis. Maecenas sed blandit leo. Proin vitae cursus ipsum, eget mollis arcu. Aenean pharetra dolor vitae interdum egestas. Nulla vitae ultrices felis. Nunc consectetur odio in mi ornare consectetur.
         Duis nec erat sem. Nulla facilisi. Donec non tincidunt justo. Aliquam et leo tincidunt, laoreet mauris vel, feugiat eros. Nulla orci libero, sollicitudin et luctus nec, consectetur sagittis ipsum. Quisque mollis, dui eu tempor varius, leo orci scelerisque sapien, eget varius nunc felis dignissim felis. Duis efficitur elit sed nibh efficitur porttitor. Suspendisse quis semper leo. Pellentesque et suscipit nulla, tincidunt faucibus velit. Curabitur id placerat felis. Praesent pellentesque massa ligula, eu iaculis massa placerat non. Phasellus luctus feugiat turpis quis tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
         Aliquam posuere lectus non mi molestie iaculis. Nunc sem mi, congue vitae vehicula at, venenatis eget dui. Proin congue augue massa, eu egestas metus tempus volutpat. Nunc ex ex, fermentum vestibulum vehicula eu, vulputate eu est. Maecenas commodo neque ex, vitae condimentum ex suscipit pulvinar. Fusce tempus pulvinar dolor, sit amet placerat neque iaculis sed. Mauris quis rhoncus turpis, vitae consequat elit. Proin ornare leo blandit ante ultricies mattis. Maecenas nec leo mauris. Integer venenatis magna vitae metus congue tempor. Sed eget turpis eget turpis iaculis vestibulum ac sed est. Ut malesuada purus ac odio ultricies ornare. Sed feugiat ultrices mi sit amet imperdiet. Donec ullamcorper dolor et ipsum molestie ornare. Pellentesque ac sem sem. Suspendisse lobortis rhoncus quam, at luctus sem malesuada eget.'''),
    );
  }
}
