include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    lines-of-code: 120
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:

    unnecessary_lambdas: true
    prefer_single_quotes: true
    unawaited_futures: true
    avoid_dynamic_calls: true
    always_use_package_imports: true
    require_trailing_commas: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_function_literals_in_foreach_calls: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    one_member_abstracts: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    type_init_formals: true

analyzer:
  strong-mode:
    implicit-dynamic: false

